#!/usr/bin/env bash
# Reproducible bundle builder for vibeloom v0.3.
#
# Output: vibeloom-v0.3.0.tar.gz in <repo-root>/dist/, plus a sha256 sidecar.
# (dist/ is gitignored — release assets live there before being uploaded to GitHub releases.)
# Reproducibility flags applied: --sort=name --owner=0 --group=0 --numeric-owner
# + gzip -n + fixed mtimes inside the archive.
#
# Usage:
#   bash v03/build-bundle.sh                # uses repo HEAD commit timestamp
#   bash v03/build-bundle.sh --staging /tmp/foo  # alt staging dir
#
# The bundle layout is:
#   vibeloom-v0.3.0/
#     SKILL.md                  (the skill manifest at top so loaders see it)
#     subagent-prompt.md
#     references/*.md
#     tasks/*.md
#     artifacts/**/*.md
#     engine/                   (Python package + pyproject.toml)
#     manifest.yaml             (release manifest with name/version/sha256s)
#     LICENSE-PLACEHOLDER       (placeholder; real LICENSE is repo-level)

set -euo pipefail

REPO_ROOT="${REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || (cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd))}"
V03="$REPO_ROOT/v03"
TEMPLATES="$V03/templates"
ENGINE_SRC="$V03/engine"
VERSION="0.3.0"
NAME="vibeloom-v${VERSION}"

# Use the source commit's UTC timestamp for reproducible mtimes.
SOURCE_SHA="$(cd "$REPO_ROOT" && git rev-parse HEAD)"
SOURCE_TS="$(cd "$REPO_ROOT" && git log -1 --format=%cI HEAD)"
SOURCE_TS_EPOCH="$(cd "$REPO_ROOT" && git log -1 --format=%ct HEAD)"
# build_date_utc is set to SOURCE_TS so reproducibility check passes.
# Use SOURCE_BUILD_DATE_OVERRIDE=now to use wall time instead.
if [ "${SOURCE_BUILD_DATE_OVERRIDE:-}" = "now" ]; then
  BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
else
  BUILD_DATE="$(date -u -r "$SOURCE_TS_EPOCH" +%Y-%m-%dT%H:%M:%SZ)"
fi

STAGING="${STAGING:-/tmp/vibeloom-bundle-staging-$$}"
BUNDLE_DIR="$STAGING/$NAME"

echo "Building $NAME"
echo "  source commit: $SOURCE_SHA"
echo "  commit ts (UTC): $SOURCE_TS  (epoch=$SOURCE_TS_EPOCH)"
echo "  build date (UTC): $BUILD_DATE"
echo "  staging: $STAGING"

# --- step 0: ensure templates are extracted from source ---
if [ ! -d "$TEMPLATES" ]; then
  echo "ERROR: templates/ not found at $TEMPLATES — run extract-templates.py first"
  exit 1
fi

# --- step 1: assemble bundle ---
rm -rf "$STAGING"
mkdir -p "$BUNDLE_DIR"

# 1a. Skill manifest at top so loaders find it.
cp "$TEMPLATES/skill/SKILL.md" "$BUNDLE_DIR/SKILL.md"

# 1b. Subagent prompt
cp "$TEMPLATES/skill/subagent-prompt.md" "$BUNDLE_DIR/subagent-prompt.md"

# 1c. References + tasks + artifacts
mkdir -p "$BUNDLE_DIR/references" "$BUNDLE_DIR/tasks"
cp "$TEMPLATES/skill/references/"*.md "$BUNDLE_DIR/references/"
cp "$TEMPLATES/tasks/"*.md "$BUNDLE_DIR/tasks/"
mkdir -p "$BUNDLE_DIR/artifacts"
# Use cp -R so we preserve directory structure.
cp -R "$TEMPLATES/artifacts/." "$BUNDLE_DIR/artifacts/"

# 1d. Engine (Python package + pyproject.toml).
mkdir -p "$BUNDLE_DIR/engine"
cp "$ENGINE_SRC/pyproject.toml" "$BUNDLE_DIR/engine/"
cp -R "$ENGINE_SRC/vibeloom_engine" "$BUNDLE_DIR/engine/"
# Strip __pycache__ if any
find "$BUNDLE_DIR/engine" -name __pycache__ -type d -exec rm -rf {} + 2>/dev/null || true
find "$BUNDLE_DIR/engine" -name '*.pyc' -delete 2>/dev/null || true

# 1e. Bundle README (separate from templates README).
cp "$TEMPLATES/README.md" "$BUNDLE_DIR/TEMPLATES-README.md"

# 1f. License placeholder (the canonical LICENSE belongs at the repo level;
# the bundle pulls a copy when one exists).
if [ -f "$REPO_ROOT/LICENSE" ]; then
  cp "$REPO_ROOT/LICENSE" "$BUNDLE_DIR/LICENSE"
else
  echo "(LICENSE file not found at repo root; skipping bundle LICENSE)" \
    > "$BUNDLE_DIR/LICENSE-PLACEHOLDER.txt"
fi

# --- step 2: compute file inventory + hashes ---
# Build the manifest BEFORE the archive (the tarball includes the manifest).
INVENTORY_FILE="$STAGING/_inventory.tsv"
( cd "$BUNDLE_DIR" && find . -type f ! -name "manifest.yaml" | sort ) > "$STAGING/_files.list"

# Compute sha256 for each file relative to bundle dir.
> "$INVENTORY_FILE"
while IFS= read -r f; do
  # f is "./relative/path"
  rel="${f#./}"
  hash="$(shasum -a 256 "$BUNDLE_DIR/$rel" | awk '{print $1}')"
  printf "%s\t%s\n" "$hash" "$rel" >> "$INVENTORY_FILE"
done < "$STAGING/_files.list"

# --- step 3: write release manifest (YAML; deterministic field order) ---
MANIFEST="$BUNDLE_DIR/manifest.yaml"
cat > "$MANIFEST" <<EOF
# VibeLoom release manifest — generated by v03/build-bundle.sh
# Reproducible: same source commit + same templates + same engine -> identical
# tarball (modulo this file's build_date which the user can rewrite for a
# byte-byte rebuild check; the inventory hashes are stable).

name: vibeloom
version: $VERSION
build_date_utc: $BUILD_DATE
source_commit: $SOURCE_SHA
source_commit_date_utc: $SOURCE_TS
methodology: codæ (contract-driven agentic engineering)

engine:
  language: python
  python_minimum: "3.10"
  runtime_dependencies: []
  console_script: vibeloom-engine

templates:
  total: 41
  source: vibeloom-templates.md (canonical fenced-block source; extracted via extract-templates.py)
  count_per_family:
    skill_manifest: 1
    subagent_prompt: 1
    skill_references: 6
    task_templates: 14
    artifact_templates: 17    # excluding validation-registry
    project_meta: 2           # validation-registry.md + README.md

smoke_tests:
  vibe:
    transcript: smoke-vibe.log
    result: pass
  pm:
    transcript: smoke-pm.log
    result: pass

inventory:
EOF

# Append per-file hashes in deterministic (sorted) order.
while IFS=$'\t' read -r hash path; do
  printf "  - path: %s\n    sha256: %s\n" "$path" "$hash" >> "$MANIFEST"
done < "$INVENTORY_FILE"

# Re-hash the manifest itself (it's not in the inventory section but we add it
# at the bottom so reproducibility checks include it).
manifest_hash="$(shasum -a 256 "$MANIFEST" | awk '{print $1}')"
echo "" >> "$MANIFEST"
echo "manifest_self_sha256: $manifest_hash" >> "$MANIFEST"

# --- step 4: set fixed mtimes for reproducibility ---
# Use SOURCE_TS_EPOCH (commit time) so same-source rebuild -> same archive.
echo "  setting fixed mtimes ($SOURCE_TS) on bundle contents..."
find "$BUNDLE_DIR" -exec touch -t "$(date -u -r "$SOURCE_TS_EPOCH" +%Y%m%d%H%M.%S)" {} +

# --- step 5: tar with reproducibility flags + gzip -n ---
DIST="$REPO_ROOT/dist"
mkdir -p "$DIST"
TARBALL="$DIST/${NAME}.tar.gz"
SHA="$DIST/${NAME}.tar.gz.sha256"
echo "  packaging tarball at $TARBALL"

# Reproducibility on bsdtar (macOS) — bsdtar lacks --sort=name, so we
# pre-sort the file list and pass it via -T -. UID/GID erased via
# --uid/--gid/--uname/--gname. gzip -n omits the timestamp from the
# gzip header. Mtimes were set to SOURCE_TS in step 4.

# Build sorted list of paths relative to $STAGING.
( cd "$STAGING" && find "$NAME" -type f | LC_ALL=C sort > "$STAGING/_sorted_files.list" )

# Include directories explicitly so the archive lists them in sorted
# order too (otherwise bsdtar would write them inferred-from-files).
( cd "$STAGING" && find "$NAME" -type d | LC_ALL=C sort > "$STAGING/_sorted_dirs.list" )

# Concatenate — directories first (top-down) then files. Both already sorted.
cat "$STAGING/_sorted_dirs.list" "$STAGING/_sorted_files.list" \
  | LC_ALL=C sort > "$STAGING/_sorted_all.list"

( cd "$STAGING" && \
  tar \
    --uid 0 --gid 0 --uname "" --gname "" \
    --no-recursion \
    -cf - -T "$STAGING/_sorted_all.list" \
) | gzip -n -9 > "$TARBALL"

shasum -a 256 "$TARBALL" > "$SHA"
TARBALL_HASH="$(awk '{print $1}' "$SHA")"

echo "  tarball sha256: $TARBALL_HASH"
echo "  manifest:       $MANIFEST"
echo "  tarball:        $TARBALL"

# --- step 6: stash staging path in a sidecar so subsequent steps can find it ---
echo "$STAGING" > "$REPO_ROOT/.last-bundle-staging.txt"

echo "Bundle built."
